# Generated by Django 5.0.4 on 2024-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
