# Generated by Django 5.0.4 on 2024-11-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_templates', '0004_alter_client_logo_alter_template_greeting_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='client',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='poster_templates.client'),
            preserve_default=False,
        ),
    ]
